openapi: 3.0.1
info:
  title: Course Management
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /createCourse:
    post:
      operationId: postCreatecourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInfo'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /updateCourse:
    put:
      operationId: putUpdatecourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInfo'
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /createLecturer:
    post:
      operationId: postCreatelecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LecturerInfo'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /updateLecturer:
    put:
      operationId: putUpdatelecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LecturerInfo'
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /deleteLecturerByStaffNo/{staffNumber}:
    delete:
      operationId: deleteDeletelecturerbystaffnoStaffnumber
      parameters:
      - name: staffNumber
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /addCourse:
    post:
      operationId: postAddcourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCourseInfo'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /addLecturer:
    post:
      operationId: postAddlecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddLecturerInfo'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /retrieveLecturerById/{staffNumber}:
    get:
      operationId: getRetrievelecturerbyidStaffnumber
      parameters:
      - name: staffNumber
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LecturerInfo'
  /retrieveLecturerByCourse:
    get:
      operationId: getRetrievelecturerbycourse
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /retrieveLecturerByOfficeNo:
    get:
      operationId: getRetrievelecturerbyofficeno
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    LecturerInfo:
      required:
      - courseCode
      - officeNumber
      - staffName
      - staffNumber
      - staffTitle
      type: object
      properties:
        staffNumber:
          type: string
        staffName:
          type: string
        staffTitle:
          type: string
        courseCode:
          type: string
        officeNumber:
          type: string
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    AddCourseInfo:
      required:
      - courseCode
      - courseId
      - staffNumber
      type: object
      properties:
        courseId:
          type: string
        staffNumber:
          type: string
        courseCode:
          type: string
    AddLecturerInfo:
      required:
      - courseCode
      - lecturerId
      - officeNumber
      - staffNumber
      type: object
      properties:
        lecturerId:
          type: string
        staffNumber:
          type: string
        courseCode:
          type: string
        officeNumber:
          type: string
    CourseInfo:
      required:
      - courseCode
      - courseDepartment
      - courseName
      - courseNQFLevel
      type: object
      properties:
        courseCode:
          type: string
        courseName:
          type: string
        courseNQFLevel:
          type: string
        courseDepartment:
          type: string
